### ISSUE TITLE
python setup.py install doesnot work on windows 10

### ISSUE THREAD

**Issue by pawarvishal** [pythonpune/linkstatus#15]
(.venv) C:\OSS\linkstatuspune\linkstatus>python setup.py install
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    readme = readme_file.read()
  File "C:\OSS\linkstatuspune\linkstatus\.venv\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1229: character maps to <undefined>

**Comment by raukadah** [comment]
Thank you @pawarvishal for the bug reporting,

**Comment by amolkahat** [comment]
Fixed in #16

**Comment by digitronik** [comment]
@pawarvishal thanks for issue added tests environment which will cover windows setup

https://github.com/pythonpune/linkstatus/pull/21
