### ISSUE TITLE
linkstatus -h does not work , works only with --help flag

### ISSUE THREAD

**Issue by raukadah** [pythonpune/linkstatus#17]
```
(.venv) [raukadah@ironman linkstatus]$ linkstatus -h
Usage: linkstatus [OPTIONS] [SOURCE]...
Try "linkstatus --help" for help.

Error: no such option: -h
```
linkstatus -h needs to be working.

**Comment by digitronik** [comment]
@raukadah thanks for issue... its not bug. but yes issue. adding some explanation which need to fix. 
```
(env) ~/P/l/tests ❯❯❯ linkstatus --help
Usage: linkstatus [OPTIONS] [SOURCE]...

  Check Link Status

Options:
  -r, --recursive        Include all files from directories recursively
  -t, --timeout INTEGER  Request timeout (default 4 second)
  -rt, --retry INTEGER   Retry link status (default 2 time)
  --help                 Show this message and exit.
```

**Comment by digitronik** [comment]
If no arg provided (file/dir) then it should not show trackback as fallow. It should show `help` menu
(env) ~/P/l/tests ❯❯❯ linkstatus
===================================================================================================================================================
                                                                Links Status Summary                                                               
                                                                    Links UP: 0                                                                    
                                                                   Links SKIP: 0                                                                   
                                                                   Links DOWN: 0                                                                   
===================================================================================================================================================
